### ISSUE TITLE
Esc not working when no result

### ISSUE THREAD

**Issue by sunshineplan** [TarekRaafat/autoComplete.js#157]
index.html
```
<script src='https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@8.1.0/dist/js/autoComplete.min.js'></script>
<input id='search'>
<script>
  const autoCompletejs = new autoComplete({
    selector: '#search',
    data: {
      src: async () => {
        if (search.value == 'test') return ['test']
        return []
      }
    },
    trigger: { event: ['input', 'focus'] },
    searchEngine: (query, record) => {
      return record
    },
    placeHolder: 'Search',
    threshold: 2,
    debounce: 300,
    maxResults: 10,
    noResults: (dataFeedback, generateList) => {
      generateList(autoCompletejs, dataFeedback, dataFeedback.results)
      const result = document.createElement('li')
      result.innerHTML = 'No Results'
      document.querySelector('#autoComplete_list').appendChild(result)
    },
    onSelection: (feedback) => {
      console.log(feedback)
    },
  })
</script>
```

Above code only show result when type 'test', otherwise will show no result.
Esc only work when typing 'test', it will clear the search bar, when no result it do nothing.
I'm using windows 10 and latest Chrome.

**Comment by TarekRaafat** [comment]
Hello @sunshineplan,

Good catch!

That was an issue with the [codepen](https://codepen.io/tarekraafat/pen/rQopdW?editors=0010) demo code but I've fixed it now, and it should be working fine.

Please check it and let me know how it's working.


Have a nice day, cheers! :)

**Comment by sunshineplan** [comment]
Hello @TarekRaafat
I found the demo works well. But still not working use my code above.
I save these code as html file directly, and use chrome to open it. Did I miss something?

**Comment by TarekRaafat** [comment]
@sunshineplan, I'll check it and get back to you asap.

**Comment by jerrykan** [comment]
I was hitting this issue as well. It seems that if the first key press returns no results then the code to handle the escape key being pressed never gets invoked/initiated.

You can see this in action on the [codepen](https://codepen.io/tarekraafat/pen/rQopdW?editors=0010) example if the first character you type in is a symbol like `!a` or `@b`. Pressing the escape after entering one of those strings results in the dropdown list not being closed.

However if you enter `a!` or `b@` then press escape the dropdown list will be closed.

The problem seems to be at:

https://github.com/TarekRaafat/autoComplete.js/blob/efee59aa624998182e2d565454afc138849bc7c9/src/autoComplete.js#L131

which returns before the following is called:

https://github.com/TarekRaafat/autoComplete.js/blob/efee59aa624998182e2d565454afc138849bc7c9/src/autoComplete.js#L141

**Comment by TarekRaafat** [comment]
The issue got fixed in [v9.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v9.0.0)
