### ISSUE TITLE
onSelection is not fired

### ISSUE THREAD

**Issue by iNalgiev** [TarekRaafat/autoComplete.js#205]
Hi,

Using the latest version (9.0.1).

**Describe the bug**
The function **onSelection** does not seem to be fired after selecting any selection in my results. This happened after updating to the latest version.

**Additional context (optional)**
Here's my config.

```javascript
const autoCompleteJS = new autoComplete({
        data: {                              // Data src [Array, Function, Async] | (REQUIRED)
            src: async () => {
                // User search query
                const query = document.querySelector("#autoComplete").value;
                // Fetch External Data Source
                const source = await fetch(apiRoot+namespace+`/a-z-list/search?term=${query}`);
                // Format data into JSON
                const data = await source.json();
                // Post Loading placeholder text
                document.querySelector("#autoComplete").setAttribute("placeholder", autoCompleteJS.placeHolder);

                // Return Fetched data
                return data.data;
            },
            key: ["naam"],
            /*results: (list) => {
                // Filter duplicates
                const filteredResults = Array.from(new Set(list.map((value) => value.match))).map((naam) => {
                    // disabled because it prevents duplicates from showing.

                    return list.find((value) => value.match === naam);
                });

                return filteredResults;
            },*/
            cache: false
        },
        placeHolder: "",     // Place Holder text                 | (Optional)
        selector: "#autoComplete",           // Input field selector              | (Optional)
        observer: true,                      // Input field observer | (Optional)
        threshold: 1,                        // Min. Chars length to start Engine | (Optional)
        debounce: 300,                       // Post duration for engine to start | (Optional)
        searchEngine: "strict",              // Search Engine type/mode           | (Optional)
        diacritics: true,
        resultsList: {
            noResults: (list,query)=>{
                // No Results List Message
                const message = document.createElement("li");
                message.setAttribute("class", "no_result");
                message.setAttribute("tabindex", "1");
                message.innerHTML = `<span style="display: flex; align-items: center; font-weight: 100; color: rgba(0,0,0,1);padding: 5px 5px;font-size: 16px;font-style: italic;">Geen resultaten gevonden voor "${query}"</span>`;
                list.appendChild(message);
            },
            maxResults: 1000,                         // Max. number of rendered results | (Optional)
        },
        trigger: {
            event: ["input", "focus"],
        },
        highlight: {
            render: true
        },                       // Highlight matching results      | (Optional)
        resultItem: {
            content: (data, element) => {
                // Modify Results Item Style
                element.style = "display: flex; justify-content: space-between;";
                // Modify Results Item Content
                element.innerHTML = `
        <span style="text-overflow: ellipsis; white-space: initial; line-height: 2em; overflow: hidden;">
            ${data.match}
        </span>
        <span style="display: flex; align-items: center; font-size: 13px; font-weight: 100; text-transform: uppercase; color: rgba(0,0,0,.6);">
            ${data.value.pod_label}
        </span>`;
            },
            highlight: {
                render: true,
            },
        },
        onSelection: feedback => {
            document.querySelector("#autoComplete").blur();
            // Prepare User's Selected Value
            const selection = feedback.selection.value[feedback.selection.key];
            // Replace Input value with the selected value
            document.querySelector("#autoComplete").value = selection;
            // Redirect page to selected filter
            // if(feedback.selection.value.type !== 'resource') {
            window.location.href = window.wpApiSettings.site_url+'/?type='+feedback.selection.value.type+'&id='+feedback.selection.value.id;
            // }
        },
    });
```

Any idea's what might be causing this issue?

**Comment by TarekRaafat** [comment]
Hello @iNalgiev,

I've tried replicating the mentioned behavior in different environments, but unfortunately, I couldn't replicate it.

Do you get the same behavior using the [demo](https://tarekraafat.github.io/autoComplete.js/demo/) or [CodePen](https://codepen.io/tarekraafat/pen/rQopdW?editors=0010)?

**Comment by TarekRaafat** [comment]
My bad, I've been trying to replicate only using the keyboard which works, but the bug exists using with the mouse interaction I'm currently working on the fix.

**Comment by TarekRaafat** [comment]
@iNalgiev the issue has been fixed in [v9.0.2](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v9.0.2)

Please try it and let me know how it goes.

**Comment by alephnull** [comment]
I've tried both v9.0.2 and v9.0.3 from the cdn but the problem persists. The lack of mouse selection causes it to be non-functional on mobile.

http://home.alephnull.site/gitaligned if you'd like to see the problem.

**Comment by TarekRaafat** [comment]
Hello @alephnull,

I've checked the link and I can see that you're using `v9.0.1` for JS and `v9.0.2` for CSS, you need to use `v9.0.3` for JS instead.

Please try it and let me know how it goes.

![Screenshot 2021-04-17 10 33 23 AM](https://user-images.githubusercontent.com/3501930/115107127-371d9480-9f69-11eb-8c60-e9f39a3162c1.png)

**Comment by alephnull** [comment]
Oops, my bad. Confirmed that it is fixed on 9.0.2. Thank you for the speedy fix!

**Comment by TarekRaafat** [comment]
No worries, you're most welcome!

Have a nice day :)
