### ISSUE TITLE
selection event handler doesn't seem to work with FireFox... ?

### ISSUE THREAD

**Issue by KOROKORO-Manbo** [TarekRaafat/autoComplete.js#3]
Tried your 'Demo' with my browser, 'FireFox 63.0.3'(OSX Mojave),
selected item didn't appear in '.selection'.
It works well with Chrome.
What's wrong  with this?

**Comment by TarekRaafat** [comment]
I checked it, obviously I changed the library name in the webpack file which lead to a failure in loading the library that's why it wasn't working.

It should be fixed now, please try the new patch release <a href="https://github.com/TarekRaafat/autoComplete.js/releases/tag/v1.0.2">`v1.0.2`</a> and let me know how it went with you.

**Comment by KOROKORO-Manbo** [comment]
thaks a lot, but it's not fixed yet ...
here is what I did ...
>DownLoad zip file (1.0.2) & extract
> npm install & npm build 
> check ./dist/index.htm
 and then, selected item didn't appear ...
I wonder why ?

FYI, 'Try me ...' and items of the array in index.js are displayed 
in input#autoComplete when it's focused.
That tells us 'autoComplete.js' is working well basically, doesn't it? 
I want to delve into scripts, but not now ...

**Comment by TarekRaafat** [comment]
You're welcome anytime, my bad I opened the issue again.

I'm currently looking into it again, I have an initial guess:
* Could be side effect of the `focus, blur` eventlistener on `.autoComplete_results_list`
which hides the container before picking up your selection

I let you know as soon as I find out something solid.

**Comment by TarekRaafat** [comment]
@KOROKORO-Manbo check the [v1.5.2](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v1.5.2) release [demo](https://tarekraafat.github.io/autoComplete.js/demo/) and let me know if your issue got fixed or not yet.

**Comment by KOROKORO-Manbo** [comment]
Thank you for fixing !
It works perfectly

**Comment by alvaaz** [comment]
In Firefox, the last version ~2.0 event is not defined yet.
we solve with: 

**autoComplete.js**

```
...
selection.addEventListener("mousedown", function (event) {
        callback(event, {
          query: getInput(field).value,
          results: resultsValues.map(function (record) {
            return record.source;
          }),
...
```

**index.js**

```
...
const autoCompletejs = new autoComplete({
		...
		onSelection: (event, feedback) => {
		}
	});
...
```

**Comment by TarekRaafat** [comment]
@alvaaz Correct me please if I got it wrong, you mean that the `Feedback` needs to return the `Event Object` instead of just the `Event Name`.

If I got it right , then true I agree with you and I've added it to the coming version.

**Comment by g-viet** [comment]
@TarekRaafat 
It doesn't work on IE11 windows 7. It seems `mousedown` event not to be supported.
Any idea ?
