### ISSUE TITLE
required settings & data.filter

### ISSUE THREAD

**Issue by jnz31** [TarekRaafat/autoComplete.js#39]
hii
first off, thanks for this tool, i finally got it working after running into multiple issues. 
works now, lucky day :)

i found a bug, or rather missleading documentation:
TypeError: config.resultsList is undefined
you get that error, when you leave out the settings for resultsList
same goes for resultItem.
when you do not define those, it throws this error. not an issue after all, but it is stated in the docs, that these are mandatory.. guess the defaults are not populated..?

**Comment by TarekRaafat** [comment]
Hello @jnz31,

I'm glad you managed to figure it out!

It's fixed now in the current new release [v.5.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v5.0.0), [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js) & [CDN](https://www.jsdelivr.com/package/gh/TarekRaafat/autoComplete.js).

Check it and let me know your thoughts or if you have any other issues.

Cheers! :)

**Comment by jnz31** [comment]
ciao tarek and thanks for the quick reply. but nope, i can't confirm that, i still get the same error..

**Comment by TarekRaafat** [comment]
Correct me if i'm wrong, you're facing issue getting an error of `TypeError: config.resultsList is undefined` when you don't populate the following keys/properties `resultsList` and `resultsItem` and leave them out blank.

If I got you right, then that's totally normal because `(Optional)` definition means that you don't use the key/property to begin with not to having it and leaving it blank.

So if you're using the any key/property and leaves it blank without populating it because it's optional that doesn't work, you have to disregard the entire key/property instead.

Hope that answers your question.

Have a good day! :)

**Comment by jnz31** [comment]
you are absolutely correct.. if i leave the complete key/pair out, i get the error..

i’m not populating the key with no/empty property..

have nice weekend

**Comment by jnz31** [comment]
hey tarek. you where correct with your fixing, i realized it was the server caching. never worked with that current environment and just realized overwriting files does not overwrite.. n-e-how, the issue is fixed.

i had another problem and i'm seriously no crack, so no clue, what the issue was, but i solved it on my end. i'm loading a json array and it works fine, but when entering a search string, console threw me errors of data.filter is not a function. that happens if your data is not an array. in my case it was a promise. funny enough, the returned data from data setting was an array (as it should be). but `var dataSrc = this.data.src();` returned a promise. and `dataSrc instanceof Promise` returned false. i now got rid of that check and it works for me. 
really no clue, what the problem is. i found [this](https://stackoverflow.com/questions/27746304/how-do-i-tell-if-an-object-is-a-promise) though, but am not fit enough to implement it into the code..
